import Layout from "../components/layout";
import Head from "next/head";
import { TOKEN, DATABASE_ID } from "../config/index.js";

export default function Projects() {
  return (
    <Layout>
      <Head>
        <title>포트폴리오</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Layout>
  );
}
//빌드 타임에 호출
export async function getStaticProps() {
  const options = {
    method: "POST",
    headers: {
      Accept : "application/json",
      "Notion-Version": "2022-02-22",
      "Content-Type": "application/json",
      Authorization : `Bearer ${TOKEN}`,
    },
    body: JSON.stringify({ page_size: 100 }),
  };

  const res = await fetch(
    `https://api.notion.com/v1/databases/${DATABASE_ID}/query`,
    options
  );

  const projects = await res.json();

  console.log(projects.results);

    const projectIds = projects.results.map((project) => project.id);

    console.log(`projectIds : ${projectIds}`);

    return {
      props: {}, // will be passed to the page component as props
}
}
